export type Language = "ar" | "en";

// Legacy Arabic-to-English entries retained for template UI compatibility.
export const translations: Record<string, string> = {
  "الرئيسية": "Home",
  "جنا عادل": "Jana Adel",
  "خبيرة وسائل التواصل الاجتماعي وصانعة محتوى ومدربة تسويق رقمي": "Social media expert, content creator, and digital marketing trainer",
  "عن جنا": "About",
  "دراسات الحالة": "Case studies",
  "صناعة المحتوى": "Content creation",
  "محتوى يحوّل الاهتمام إلى تأثير.": "Social media that turns attention into action.",
  "أعمال مختارة في المحتوى والاستراتيجية": "Selected content and strategy work",
  "نبذة": "Introduction",
  "لنعمل معاً": "Let's work together",
  "الخبرات العملية": "Work experience",
  "التعليم والشهادات": "Education & certifications",
  "مجالات الخبرة": "Core expertise",
  "إدارة وسائل التواصل الاجتماعي": "Social media management",
  "أبحاث التسويق ورؤى الجمهور": "Marketing research & insights",
  "استراتيجية السوق": "Market strategy",
  "دراسات الحالة والأعمال الاستراتيجية – جنا عادل": "Case studies & strategic work – Jana Adel",
  "معرض صناعة المحتوى – جنا عادل": "Content creation showcase – Jana Adel",
  "محتوى أصلي من صناعة جنا": "Original content creation",
  "دليل تخطيط الحمام": "Bathroom planning guide",
  "خطط لجدار التلفزيون قبل التشطيب": "Plan the TV wall before finishing",
  "اختر السماد بثقة": "Choose fertilizer with confidence",
  "لماذا تصفر الأوراق الجديدة؟": "Why new leaves turn yellow",
  "التعريف بمنتج كيوب كيه": "Cube-K product awareness",
  "رسالة نمو جديدة": "A new-growth brand message",
  "تجنب مشكلات السباكة مبكراً": "Prevent plumbing problems early",
  "توعية عملية للعناية بالمحاصيل": "Practical crop-care education",
  "سرد بصري للعلامة الزراعية": "Agricultural brand storytelling",
  "تسليط الضوء على فائدة المنتج": "Product benefit spotlight",
  "تصميم رسالة الحملة": "Campaign message visual",
  "مرجع الهوية البصرية": "Brand identity reference",
  "عرض دراسة الحالة": "Read case study",
  "دراسات حالة ذات صلة": "Related case studies",
  "الصفحة غير موجودة": "Page not found",
  "الصفحة التي تبحث عنها غير موجودة.": "The page you are looking for does not exist.",
  "احجز مكالمة": "Schedule a call",
  "كلمة المرور": "Password",
  "إرسال": "Submit",
  "تواصل عبر واتساب": "Contact on WhatsApp",
  "سيظهر زر واتساب هنا بعد إضافة الرقم في إعدادات الملف الشخصي.": "A WhatsApp button will appear here once the number is added to the profile settings.",
  "أحدث المقالات": "Latest articles",
  "قالب دراسة حالة لحملة على وسائل التواصل الاجتماعي، يشمل الموجز ونهج المحتوى وخطة القنوات والنتائج.": "A social media campaign case-study template covering the brief, content approach, channel plan, and results.",
  "قالب دراسة حالة بحثية يوضح كيف شكّلت رؤى السوق والجمهور والمنافسين توصية تسويقية.": "A research case-study template showing how market, audience, and competitor insight shaped a marketing recommendation.",
  "قالب عمل استراتيجي يوضح كيف تحولت الأبحاث إلى خطة للسوق والقنوات والمحتوى.": "A strategic-work template showing how research became a market, channel, and content plan.",
  "نبذة عن الحملة": "Campaign overview",
  "التحدي": "The challenge",
  "الاستراتيجية والتنفيذ": "Strategy & execution",
  "أمثلة على المحتوى": "Content examples",
  "النتائج": "Results",
  "الخلاصة الرئيسية": "Key takeaway",
  "نبذة عن البحث": "Research overview",
  "سؤال البحث": "Research question",
  "المنهجية": "Approach",
  "الرؤى الرئيسية": "Key insights",
  "التوصية": "Recommendation",
  "نبذة عن الاستراتيجية": "Strategy overview",
  "السياق": "Context",
  "التوجه الاستراتيجي": "Strategic direction",
  "المخرجات": "Deliverables",
  "خطة القياس": "Measurement plan",
  "مؤشرات أداء نموذجية": "Sample performance KPIs",
};

const legacyEnglishToArabic = Object.fromEntries(
  Object.entries(translations).map(([arabic, english]) => [english, arabic]),
);

// Portfolio copy is authored in English so that it renders natively on first load.
const englishToArabic: Record<string, string> = {
  ...legacyEnglishToArabic,
  "Jana": "جنا",
  "Adel": "عادل",
  "Jana Adel": "جنا عادل",
  "Social media expert, content creator, and digital marketing trainer": "خبيرة وسائل التواصل الاجتماعي وصانعة محتوى ومدربة تسويق رقمي",
  "Home": "الرئيسية",
  "About": "عن جنا",
  "Case studies": "دراسات الحالة",
  "Content creation": "صناعة المحتوى",
  "Content that turns attention into action.": "محتوى يحوّل الاهتمام إلى تأثير.",
  "Selected content and strategy work": "أعمال مختارة في المحتوى والاستراتيجية",
  "I'm Jana, a social media expert, content creator, and digital marketing trainer. I help brands and individuals develop clear messaging, effective content, and marketing strategies grounded in audience and market insight.": "أنا جنا، خبيرة وسائل التواصل الاجتماعي وصانعة محتوى ومدربة تسويق رقمي. أساعد العلامات التجارية والأفراد على بناء رسائل واضحة ومحتوى فعّال واستراتيجيات تسويقية قائمة على فهم الجمهور والسوق.",
  "About Jana Adel": "عن جنا عادل",
  "Introduction": "نبذة",
  "Let's work together": "لنعمل معاً",
  "Work experience": "الخبرات العملية",
  "Education and certifications": "التعليم والشهادات",
  "Core expertise": "مجالات الخبرة",
  "Jana is a social media expert, content creator, and digital marketing trainer who combines audience insight, compelling storytelling, and practical strategy. Her experience spans operations, marketing research, content writing, campaign management, and digital-marketing training for young people and students.": "جنا خبيرة في وسائل التواصل الاجتماعي وصناعة المحتوى ومدربة تسويق رقمي، تجمع بين فهم الجمهور والسرد المؤثر والاستراتيجية العملية. لديها خبرة في إدارة العمليات، وأبحاث السوق، وكتابة المحتوى، وإدارة الحملات، وتدريب الشباب والطلاب على التسويق الرقمي.",
  "For collaborations, campaigns, or research projects:": "للتعاون أو الحملات أو مشاريع الأبحاث:",
  "WhatsApp:": "واتساب:",
  "LinkedIn:": "لينكدإن:",
  "November 2021 – present · Part-time": "نوفمبر 2021 – حتى الآن · دوام جزئي",
  "Online trainer": "مدربة عبر الإنترنت",
  "Train young people on the network's subjects through online learning and interactive platforms.": "تدريب الشباب على موضوعات الشبكة باستخدام منصات تعليمية وتفاعلية عبر الإنترنت.",
  "Use tools including Kahoot, Padlet, Nearpod, Mentimeter, Google Classroom, ClassPoint, and Wordwall.": "استخدام أدوات مثل Kahoot وPadlet وNearpod وMentimeter وGoogle Classroom وClassPoint وWordwall.",
  "Youth Qualification for Self-employment Project – Modern European Academy": "مشروع تأهيل الشباب للتوظيف الذاتي – الأكاديمية الأوروبية الحديثة",
  "October 2020 – present · Part-time": "أكتوبر 2020 – حتى الآن · دوام جزئي",
  "Digital marketing trainer": "مدربة تسويق رقمي",
  "Train students in marketing fundamentals, marketing plans and strategy, market research, ideal-customer definition, and customer journeys.": "تدريب الطلاب على أساسيات التسويق وخطة واستراتيجية التسويق وأبحاث السوق وتحديد العميل المثالي ورحلة العميل.",
  "Deliver practical training in social channels, content, campaign monitoring, and advertising across Facebook, Instagram, X, and more.": "تقديم تدريب عملي على القنوات الاجتماعية والمحتوى ومراقبة الحملات والإعلانات عبر فيسبوك وإنستغرام وX وغيرها.",
  "February 2019 – present": "فبراير 2019 – حتى الآن",
  "Operations manager": "مديرة عمليات",
  "Manage and supervise an integrated team and prepare reports.": "إدارة فريق عمل متكامل والإشراف عليه وإعداد التقارير.",
  "Write and publish content for company clients, developing original content through social listening and independent sources.": "كتابة المحتوى ونشره لعملاء الشركة، وتطوير محتوى أصلي عبر الاستماع الاجتماعي والمصادر المستقلة.",
  "Improve content quality through review, editing, and industry-news monitoring.": "تعزيز جودة المحتوى بالمراجعة والتحرير ومتابعة أخبار الصناعة ومصادرها.",
  "Horus Trading and Agricultural Development": "حورس للتجارة والتنمية الزراعية",
  "August 2019 – January 2020": "أغسطس 2019 – يناير 2020",
  "Public relations specialist and marketing officer": "أخصائية علاقات عامة ومسؤولة تسويق",
  "Design and deliver campaign assets, including email invitations, articles, and marketing videos.": "تصميم وتنفيذ مخرجات الحملات، بما فيها الدعوات البريدية والمقالات والفيديوهات التسويقية.",
  "Conduct market analysis, monitor competitor activity, and manage internal, external, and crisis communications.": "إجراء تحليل السوق ومتابعة نشاط المنافسين وإدارة الاتصالات الداخلية والخارجية واتصالات الأزمات.",
  "Freelance": "عمل حر",
  "Social media specialist": "أخصائية وسائل التواصل الاجتماعي",
  "Prepare interactive digital presentations for managers and write professional business correspondence and update reports.": "إعداد عروض رقمية تفاعلية للمديرين وكتابة مراسلات أعمال احترافية وتقارير تحديثات.",
  "Use sales forecasting and strategic planning to support product and service profitability.": "استخدام التنبؤ بالمبيعات والتخطيط الاستراتيجي لدعم ربحية المنتجات والخدمات.",
  "Bachelor of Agriculture – Tanta University": "بكالوريوس الزراعة – جامعة طنطا",
  "Training of Trainers (TOT) – UNFPA / Y-PEER Project": "تدريب المدربين (TOT) – مشروع UNFPA / Y-PEER",
  "June 2019": "يونيو 2019",
  "Preparing agricultural engineers for greenhouse vegetable cultivation": "إعداد مهندسين زراعيين لزراعة الخضراوات تحت الصوب",
  "National Company in cooperation with the Arab Organization for Industrialization and the Ministry of Agriculture – September to November 2019": "الشركة الوطنية بالتعاون مع الهيئة العربية للتصنيع ووزارة الزراعة – سبتمبر إلى نوفمبر 2019",
  "Social media management": "إدارة وسائل التواصل الاجتماعي",
  "Plan platform-appropriate content, build content calendars, manage community engagement, and monitor campaigns.": "تخطيط محتوى مناسب لكل منصة، وبناء جداول المحتوى، وإدارة التفاعل مع المجتمع ومراقبة الحملات.",
  "Turn brand messaging and audience insight into engaging content ideas, copy, and creative direction, supported by proofreading, editing, and photography and editing tools.": "تحويل رسائل العلامة التجارية ورؤى الجمهور إلى أفكار محتوى ونصوص وتوجيه إبداعي جذاب، مع التدقيق والتحرير واستخدام أدوات التصوير والتحرير.",
  "Articles, videos, posts, presentations": "مقالات، فيديوهات، منشورات، عروض",
  "Photography and editing tools": "أدوات التصوير والتحرير",
  "Marketing research and audience insight": "أبحاث التسويق ورؤى الجمهور",
  "Study audiences, competitors, market signals, ideal customers, and customer journeys to inform content and campaign decisions.": "دراسة الجمهور والمنافسين وإشارات السوق وتحديد العميل المثالي ورحلة العميل لدعم قرارات المحتوى والحملات.",
  "Market and competitor analysis": "تحليل السوق والمنافسين",
  "Market strategy": "استراتيجية السوق",
  "Turn research into practical recommendations for positioning, channels, content, and campaigns, including business models, value propositions, and marketing plans.": "تحويل الأبحاث إلى توصيات عملية للتموضع والقنوات والمحتوى والحملات، بما يشمل نماذج الأعمال والقيمة المقترحة وخطط التسويق.",
  "Marketing plan and customer journey": "خطة التسويق ورحلة العميل",
  "Case studies and strategic work – Jana Adel": "دراسات الحالة والأعمال الاستراتيجية – جنا عادل",
  "Content creation showcase – Jana Adel": "معرض صناعة المحتوى – جنا عادل",
  "Original social content by Jana, showing how audience questions and product benefits become clear, engaging visual stories.": "محتوى أصلي من تصميم جنا لوسائل التواصل الاجتماعي، يوضح كيف تحوّل أسئلة الجمهور ومزايا المنتجات إلى قصص بصرية واضحة وجذابة.",
  "Original content by Jana": "محتوى أصلي من صناعة جنا",
  "Read case study": "عرض دراسة الحالة",
  "View project": "عرض المشروع",
  "Contact on WhatsApp": "تواصل عبر واتساب",
  "A WhatsApp button will appear here once the number is added to the profile settings.": "سيظهر زر واتساب هنا بعد إضافة الرقم في إعدادات الملف الشخصي.",
  "Latest articles": "أحدث المقالات",
  "Schedule a call": "احجز مكالمة",
  "Bathroom planning guide": "دليل تخطيط الحمام",
  "Plan the TV wall before finishing": "خطط لجدار التلفزيون قبل التشطيب",
  "Choose fertilizer with confidence": "اختر السماد بثقة",
  "Why new leaves turn yellow": "لماذا تصفر الأوراق الجديدة؟",
  "Cube-K product awareness": "التعريف بمنتج كيوب كيه",
  "A new-growth brand message": "رسالة نمو جديدة",
  "Prevent plumbing problems early": "تجنب مشكلات السباكة مبكراً",
  "Practical crop-care education": "توعية عملية للعناية بالمحاصيل",
  "Agricultural brand storytelling": "سرد بصري للعلامة الزراعية",
  "Product benefit spotlight": "تسليط الضوء على فائدة المنتج",
  "Campaign message visual": "تصميم رسالة الحملة",
  "Brand identity reference": "مرجع الهوية البصرية",
  "Educational bathroom-planning post for Ahmed Ali Finishing and Décor": "منشور تعليمي لتخطيط الحمام لصالح أحمد علي للتشطيبات والديكور",
  "TV-unit placement advice for Ahmed Ali Finishing and Décor": "نصيحة عن موضع وحدة التلفزيون لصالح أحمد علي للتشطيبات والديكور",
  "Fertilizer-choice education post for Horus": "منشور توعوي لاختيار السماد لصالح شركة حورس",
  "Educational post about yellowing leaves for Horus": "منشور تعليمي عن اصفرار الأوراق لصالح شركة حورس",
  "Cube-K product-awareness post for Horus": "منشور للتعريف بمنتج كيوب كيه لصالح شركة حورس",
  "New-growth visual-identity post for Horus": "منشور هوية بصرية للنمو الجديد لصالح شركة حورس",
  "Plumbing-preparation tip for Ahmed Ali Finishing and Décor": "نصيحة لتجهيز السباكة لصالح أحمد علي للتشطيبات والديكور",
  "Educational agricultural-product post for Horus": "منشور تعليمي لمنتج زراعي لصالح شركة حورس",
  "Social-media design for the Horus agricultural brand": "تصميم لوسائل التواصل الاجتماعي لعلامة حورس الزراعية",
  "Agricultural-product social-media design for Horus": "تصميم لمنتج زراعي على وسائل التواصل الاجتماعي لصالح حورس",
  "Agricultural social-media campaign design for Horus": "تصميم حملة زراعية على وسائل التواصل الاجتماعي لصالح حورس",
  "Ahmed Ali Finishing and Décor logo": "شعار أحمد علي للتشطيبات والديكور",
  "An educational post that turns bathroom-planning details into clear visual cues, helping prospective clients know what to consider before finishing begins.": "منشور تعليمي يحوّل تفاصيل تخطيط الحمام إلى إشارات بصرية واضحة، ليساعد العملاء المحتملين على معرفة ما يجب التفكير فيه قبل بدء التشطيب.",
  "A post that addresses a common homeowner problem with a direct headline and visual example that encourages saves and comments.": "منشور لحل مشكلة شائعة لدى أصحاب المنازل، يستخدم عنواناً مباشراً ومثالاً بصرياً لتشجيع الحفظ والتعليقات.",
  "An educational post that frames fertilizer choice as a long-term investment, using a strong visual concept to stop the scroll.": "منشور توعوي يعيد تقديم اختيار السماد كاستثمار طويل المدى، مستخدماً فكرة بصرية قوية تلفت الانتباه أثناء التصفح.",
  "A research-led educational format that answers a real audience question, explains likely causes, and positions the product as part of the solution.": "صيغة تعليمية مستوحاة من أسئلة البحث، تجيب عن سؤال حقيقي للجمهور وتشرح الأسباب المحتملة وتعرض المنتج كجزء من الحل.",
  "A concise product-awareness design with a strong headline and simple composition that make the product name and benefit easy to remember.": "تصميم موجز للتعريف بالمنتج، يستخدم عنواناً قوياً وتكويناً بسيطاً ليجعل اسم المنتج وفائدته سهلَي التذكر.",
  "A clean, product-led design that connects healthy leaves with the brand promise and builds recall while keeping the message simple.": "تصميم نظيف يقوده المنتج، يربط بين الأوراق الصحية ووعد العلامة التجارية، ويعزز التذكر مع الحفاظ على رسالة بسيطة.",
  "An educational post that highlights a hidden risk before it becomes costly, positioning the brand as a helpful expert rather than only a service provider.": "منشور توعوي يبرز خطراً خفياً قبل أن يصبح مكلفاً، ويقدم العلامة التجارية كخبير يساعد العميل لا كمجرد مقدم خدمة.",
  "An educational post that turns a product benefit into helpful, easy-to-understand guidance for an agricultural audience.": "منشور تعليمي يحوّل فائدة المنتج إلى إرشاد مفيد وسهل الفهم للجمهور الزراعي.",
  "A branded design that keeps product communication consistent across content, strengthening trust and brand recognition.": "تصميم يحمل هوية العلامة للحفاظ على اتساق التواصل عن المنتج عبر المحتوى، وتعزيز الثقة والتعرّف على العلامة.",
  "A focused content piece that presents one product benefit clearly, making it easy to read quickly on mobile social platforms.": "قطعة محتوى مركزة تقدم فائدة واحدة للمنتج بوضوح، ليكون من السهل قراءتها سريعاً على منصات التواصل عبر الهاتف.",
  "A campaign-ready design that combines product messaging with a consistent identity system to give the brand a stronger content presence.": "تصميم جاهز للحملة يجمع بين توصيل رسالة المنتج ونظام هوية متسق، ليمنح العلامة حضوراً أقوى في المحتوى.",
  "The visual identity used as the foundation for Ahmed Ali's content series, keeping every social post consistent.": "الهوية البصرية المستخدمة كأساس لسلسلة محتوى أحمد علي، للحفاظ على اتساق كل منشور على وسائل التواصل.",
  "Finishing quality starts beneath the paint": "جودة التشطيب تبدأ قبل الطلاء",
  "A striking paint-and-wall visual that positions preparation work as the difference between a temporary finish and lasting quality.": "تصميم بصري قوي يوضح أن الأعمال التحضيرية هي الفارق بين تشطيب مؤقت وجودة تدوم.",
  "Plan the electrical work before closing the wall": "خطط للأعمال الكهربائية قبل إغلاق الحائط",
  "An educational electrical-installation post that helps homeowners understand the hidden decisions that protect a finished space.": "منشور توعوي عن التركيبات الكهربائية يساعد أصحاب المنازل على فهم القرارات الخفية التي تحمي جودة المساحة بعد التشطيب.",
  "The HVAC detail that changes the outcome": "تفصيلة التكييف التي تصنع الفارق",
  "A practical visual about air-conditioning installation, turning a technical finishing detail into a clear, save-worthy customer lesson.": "تصميم عملي عن تركيب التكييف يحول تفصيلة فنية في التشطيب إلى معلومة واضحة تستحق الحفظ.",
  "The shower drainage detail to plan early": "تفصيلة صرف الدش التي يجب التخطيط لها مبكراً",
  "A bathroom-planning post that surfaces a small drainage decision before it becomes a costly problem after delivery.": "منشور لتخطيط الحمام يلفت الانتباه إلى قرار صغير في الصرف قبل أن يتحول إلى مشكلة مكلفة بعد التسليم.",
  "Protect plumbing before the tiles go in": "احمِ السباكة قبل تركيب البلاط",
  "A plumbing access visual that makes hidden infrastructure visible and strengthens the brand's expert-led positioning.": "تصميم يوضح نقاط الوصول إلى السباكة ويجعل البنية التحتية المخفية مفهومة، بما يعزز مكانة العلامة كخبير موثوق.",
  "Plan the finishing budget before the work begins": "خطط لميزانية التشطيب قبل بدء العمل",
  "A high-impact residential visual that uses cost planning as an entry point for a more informed conversation with the client.": "تصميم سكني مؤثر يستخدم التخطيط للتكلفة كبداية لحوار أكثر وعياً مع العميل.",
  "A better shower starts with drainage planning": "دش أفضل يبدأ بتخطيط الصرف",
  "An educational bathroom visual that connects a polished final space to one critical technical choice below the surface.": "تصميم توعوي للحمام يربط النتيجة الأنيقة بقرار فني أساسي تحت السطح.",
  "Inspect hidden plumbing before closing the wall": "افحص السباكة المخفية قبل إغلاق الحائط",
  "A clear pre-finishing message that helps homeowners understand why inspection matters before tiles and paint are completed.": "رسالة واضحة قبل التشطيب تساعد أصحاب المنازل على فهم أهمية الفحص قبل إتمام البلاط والطلاء.",
  "Prevent future repairs with early plumbing planning": "تجنب الإصلاحات المستقبلية بتخطيط السباكة مبكراً",
  "A practical content piece that turns a technical plumbing issue into an accessible customer education moment.": "قطعة محتوى عملية تحول مشكلة سباكة فنية إلى معلومة سهلة ومفيدة للعميل.",
  "Recessed lighting needs a precise plan": "الإضاءة المخفية تحتاج إلى تخطيط دقيق",
  "A room-design visual that demonstrates how detailed ceiling planning protects the finished ambience of a home.": "تصميم للغرفة يوضح كيف يحافظ التخطيط الدقيق للسقف على أجواء المنزل بعد التشطيب.",
  "The hidden bathroom detail that needs attention": "تفصيلة الحمام المخفية التي تحتاج إلى اهتمام",
  "A focused bathroom post that uses a concealed-cistern detail to position preventative planning as part of a quality finish.": "منشور مركز للحمام يستخدم تفصيلة خزان الطرد المخفي ليؤكد أن التخطيط الوقائي جزء من التشطيب الجيد.",
  "Control finishing costs with the right early decisions": "تحكم في تكاليف التشطيب بالقرارات الصحيحة المبكرة",
  "A cinematic interior visual that frames careful planning as the foundation for managing finishing costs successfully.": "تصميم داخلي بأسلوب سينمائي يبرز التخطيط الدقيق كأساس لإدارة تكاليف التشطيب بنجاح.",
  "The three-point kitchen layout": "مثلث المطبخ بثلاث نقاط",
  "A kitchen-planning visual that explains how the right relationship between storage, washing, and cooking makes daily movement easier.": "تصميم لتخطيط المطبخ يشرح كيف تجعل العلاقة الصحيحة بين التخزين والغسيل والطهي الحركة اليومية أكثر سهولة.",
  "Finishing and décor content reel": "فيديو محتوى التشطيبات والديكور",
  "A vertical video asset that brings the finishing-content system to life through motion, pacing, and an immediate visual hook.": "مقطع فيديو رأسي يحيي منظومة محتوى التشطيبات بالحركة والإيقاع وجاذبية بصرية فورية.",
  "Ahmed Ali finishing quality-awareness post": "منشور توعوي عن جودة التشطيب لصالح أحمد علي",
  "Ahmed Ali electrical-planning awareness post": "منشور توعوي عن تخطيط الكهرباء لصالح أحمد علي",
  "Ahmed Ali HVAC-installation awareness post": "منشور توعوي عن تركيب التكييف لصالح أحمد علي",
  "Ahmed Ali shower-drainage awareness post": "منشور توعوي عن صرف الدش لصالح أحمد علي",
  "Ahmed Ali plumbing-access awareness post": "منشور توعوي عن نقاط الوصول للسباكة لصالح أحمد علي",
  "Ahmed Ali cost-planning awareness post": "منشور توعوي عن تخطيط التكلفة لصالح أحمد علي",
  "Ahmed Ali bathroom drainage-design post": "منشور لتصميم صرف الحمام لصالح أحمد علي",
  "Ahmed Ali concealed plumbing-design post": "منشور لتصميم السباكة المخفية لصالح أحمد علي",
  "Ahmed Ali water-pipe planning post": "منشور لتخطيط مواسير المياه لصالح أحمد علي",
  "Ahmed Ali recessed-lighting planning post": "منشور لتخطيط الإضاءة المخفية لصالح أحمد علي",
  "Ahmed Ali concealed cistern awareness post": "منشور توعوي عن خزان الطرد المخفي لصالح أحمد علي",
  "Ahmed Ali finishing cost-planning post": "منشور لتخطيط تكاليف التشطيب لصالح أحمد علي",
  "Ahmed Ali kitchen layout-planning post": "منشور لتخطيط توزيع المطبخ لصالح أحمد علي",
  "Ahmed Ali Finishing and Décor social-content reel": "فيديو محتوى اجتماعي لأحمد علي للتشطيبات والديكور",
  "Additional content formats": "صيغ محتوى إضافية",
  "The campaign expanded the content system beyond static guidance, using finishing-quality, electrical-planning, and concealed-plumbing visuals to give homeowners more practical entry points into the brand.": "وسعت الحملة منظومة المحتوى إلى ما هو أبعد من الإرشادات الثابتة، باستخدام تصاميم عن جودة التشطيب وتخطيط الكهرباء والسباكة المخفية لتمنح أصحاب المنازل نقاط دخول عملية أكثر إلى العلامة التجارية.",
  "Ahmed Ali Finishing and Décor content reel": "فيديو محتوى أحمد علي للتشطيبات والديكور",
  "Your browser does not support embedded video.": "متصفحك لا يدعم تشغيل الفيديو المضمن.",
  "Educational content that builds trust in agriculture — Horus": "محتوى توعوي يبني الثقة في القطاع الزراعي — حورس",
  "A draft case study of original agricultural content: simplifying growers' questions into a consistent, branded visual series.": "مسودة دراسة حالة لأعمال المحتوى الزراعي الأصلية: تبسيط أسئلة المزارعين وتحويلها إلى سلسلة مرئية متسقة للعلامة التجارية.",
  "From customer questions to clearer finishing decisions — Ahmed Ali Finishing and Décor": "من أسئلة العميل إلى قرار تشطيب أوضح — أحمد علي للتشطيبات والديكور",
  "A draft case study for finishing-services content: using practical guidance to build trust and turn interest into higher-quality conversations.": "مسودة دراسة حالة لمحتوى خدمات التشطيبات: استخدام الإرشاد العملي لبناء الثقة وتحويل الاهتمام إلى محادثات أكثر جودة.",
  "Structured content operations for client accounts — ELADL MEDIA CO.": "تشغيل محتوى منظم لحسابات العملاء — ELADL MEDIA CO.",
  "A draft operational case study showing the value of combining team management, content quality, and continuous research to improve client-account output.": "مسودة دراسة حالة تشغيلية توضّح قيمة الجمع بين إدارة الفريق، جودة المحتوى، والبحث المستمر لتحسين مخرجات حسابات العملاء.",
  "Project overview": "نبذة عن العمل",
  "Brand:": "العلامة التجارية:",
  "Organisation:": "الجهة:",
  "Sector:": "القطاع:",
  "Jana's role:": "دور جنا:",
  "Case-study status:": "حالة الدراسة:",
  "CV period:": "الفترة في السيرة الذاتية:",
  "Agricultural inputs and services": "مدخلات وخدمات زراعية",
  "Content-topic research, copywriting, creative direction, and editorial review": "أبحاث موضوعات المحتوى، كتابة المحتوى، التوجيه الإبداعي، والمراجعة التحريرية",
  "A publishable draft; performance data and post links will be added after client approval.": "مسودة قابلة للنشر؛ تُضاف بيانات الأداء وروابط المنشورات بعد اعتماد العميل.",
  "Agricultural products need content that explains their value clearly and responsibly. This work turns practical grower questions into posts that are easy to save and share, while maintaining a distinct brand and product presence.": "المنتجات الزراعية تحتاج إلى محتوى يشرح فائدتها بوضوح وبمسؤولية. ركّز هذا العمل على تحويل الأسئلة العملية التي يواجهها المزارعون إلى منشورات سهلة الحفظ والمشاركة، مع الحفاظ على حضور واضح للعلامة التجارية والمنتج.",
  "The challenge": "التحدي",
  "Technical products cannot be explained in seconds. The audience needs useful guidance before a direct sales message, and the brand identity must stay consistent across varied topics and formats.": "منتجات ذات تفاصيل فنية لا تُشرح في ثوانٍ، وجمهور يحتاج إلى إرشاد مفيد قبل عرض بيع مباشر، مع ضرورة الحفاظ على هوية العلامة عبر موضوعات وصيغ متنوعة.",
  "Primary objective:": "الهدف الأساسي:",
  "Build trust through educational content worth saving and sharing.": "بناء الثقة عبر محتوى تعليمي قابل للحفظ والمشاركة.",
  "Target audience:": "الجمهور المستهدف:",
  "Growers and people interested in crop care.": "المزارعون ومهتمو العناية بالمحاصيل.",
  "Core channels:": "القنوات الرئيسية:",
  "Social-media posts.": "منشورات وسائل التواصل الاجتماعي.",
  "Proposed success metric:": "مؤشر النجاح المقترح:",
  "Saves, shares, messages, and qualified enquiries.": "الحفظ والمشاركة والرسائل والاستفسارات المؤهلة.",
  "Strategy and delivery": "الاستراتيجية والتنفيذ",
  "Question research:": "البحث عن الأسئلة:",
  "Identify relevant topics such as fertilizer choice, yellowing leaves, and practical crop care.": "تحديد موضوعات عالية الصلة مثل اختيار السماد، اصفرار الأوراق، والعناية العملية بالمحاصيل.",
  "Message simplification:": "تبسيط الرسالة:",
  "Build every asset around one question, one benefit, and one clear next step instead of overloading it with product information.": "بناء كل قطعة حول سؤال واحد وفائدة واحدة وخطوة تالية واضحة بدلاً من حشد معلومات المنتج.",
  "A repeatable visual system:": "نظام بصري قابل للتكرار:",
  "Use product imagery, growth cues, and concise headlines to make content recognisable in a fast scroll.": "استخدام صور المنتج وإشارات النمو وعناوين قصيرة لتسهيل التعرّف على المحتوى أثناء التصفح السريع.",
  "Quality review:": "مراجعة الجودة:",
  "Check copy and sources and follow sector news to support more credible, audience-relevant content.": "تدقيق الصياغة والمصادر ومتابعة أخبار القطاع لدعم محتوى أكثر موثوقية وملاءمة للجمهور.",
  "Content examples": "أمثلة على المحتوى",
  "The content gallery includes posts on fertilizer choice, diagnosing yellowing leaves, Cube-K product awareness, growth messaging, and agricultural brand identity.": "تظهر في معرض المحتوى منشورات عن اختيار السماد، تشخيص اصفرار الأوراق، التعريف بمنتج كيوب كيه، ورسائل النمو وهوية العلامة الزراعية.",
  "Results": "النتائج",
  "The current value of this example is demonstrating the ability to turn technical topics into scalable, structured content. This draft includes no unverified performance figures.": "القيمة الحالية للمثال هي إظهار القدرة على تحويل موضوعات تقنية إلى محتوى منظم قابل للتوسع. لا تتضمن هذه المسودة أرقام أداء غير موثقة.",
  "Sample performance KPIs": "مؤشرات أداء نموذجية",
  "Illustrative data for visual presentation only:": "بيانات افتراضية للعرض البصري فقط:",
  "This will be fully replaced with approved channel reporting before final publication.": "ستُستبدل بالكامل بتقرير القنوات المعتمد قبل النشر النهائي.",
  "Metric": "المؤشر",
  "Sample result over 90 days": "نموذج نتيجة خلال 90 يوماً",
  "Posts published": "المنشورات المنشورة",
  "Total reach": "الوصول الكلي",
  "Engagement rate": "معدل التفاعل",
  "Saves and shares": "مرات الحفظ والمشاركة",
  "Incoming messages and enquiries": "رسائل واستفسارات واردة",
  "Qualified follow-up enquiries": "استفسارات مؤهلة للمتابعة",
  "Key takeaway": "الخلاصة الرئيسية",
  "Confirming the publication period, original post links, channels used, business objective, and a snapshot of reach, engagement, and messages will turn this into a final publishable case study.": "تأكيد فترة النشر، روابط المنشورات الأصلية، القنوات المستخدمة، الهدف التجاري، ولقطة من مؤشرات الوصول والتفاعل والرسائل سيحوّل هذا النموذج إلى دراسة حالة نهائية قابلة للنشر.",
  "Residential finishing and décor": "تشطيبات وديكور سكني",
  "Content-idea development, copywriting, visual direction, and planning an educational post series": "تطوير أفكار المحتوى، كتابة النصوص، التوجيه البصري، وتخطيط سلسلة منشورات تعليمية",
  "A draft based on the showcased content examples; client approval and performance data are pending.": "مسودة مبنية على نماذج المحتوى المعروضة؛ تنتظر اعتماد العميل ومؤشرات الأداء.",
  "Finishing is a high-cost decision that depends on details clients may not consider until it is too late. The content is designed to reach them earlier: explaining what to plan, making expertise tangible, and opening a more useful conversation with the service provider.": "قرار التشطيب مرتفع التكلفة ويعتمد على تفاصيل قد لا يفكر فيها العميل إلا بعد فوات الوقت. لذلك تم بناء محتوى يسبق هذه اللحظة: يشرح ما يجب التخطيط له، ويجعل الخبرة ملموسة، ويفتح الباب لحوار أكثر فائدة مع مقدم الخدمة.",
  "Context": "السياق",
  "Business objective:": "هدف العمل:",
  "Establish expertise before the client begins execution.": "ترسيخ الخبرة قبل أن يبدأ العميل التنفيذ.",
  "Market opportunity:": "فرصة السوق:",
  "Turn recurring finishing questions into lasting marketing assets.": "تحويل الأسئلة المتكررة حول التشطيب إلى أصول تسويقية دائمة.",
  "Priority audience:": "الجمهور ذو الأولوية:",
  "Homeowners planning a finishing project or renovation.": "أصحاب المنازل الذين يخططون للتشطيب أو التجديد.",
  "Main constraint:": "القيد الرئيسي:",
  "Speak clearly to clients before a problem becomes expensive.": "مخاطبة العميل بلغة واضحة قبل أن تصبح المشكلة مكلفة.",
  "Strategic direction": "التوجه الاستراتيجي",
  "Choose decision moments:": "اختيار لحظات القرار:",
  "Bathroom planning, plumbing, and TV walls—topics that affect comfort and cost after handover.": "حمام، سباكة، وجدار تلفزيون؛ وهي موضوعات تؤثر في الراحة والتكلفة بعد التسليم.",
  "Problem-before-solution format:": "صيغة المشكلة قبل الحل:",
  "A direct headline gets attention, followed by practical guidance and an invitation to consult early.": "عنوان مباشر يلفت الانتباه، ثم نصيحة قابلة للتطبيق، ثم دعوة للاستشارة المبكرة.",
  "Brand consistency:": "تناسق العلامة:",
  "Unify visual cues and give advice in a practical tone that improves recall and trust.": "توحيد الإشارات البصرية وتقديم النصيحة بنبرة عملية تعزز التذكر والثقة.",
  "Conversion readiness:": "قابلية التحويل:",
  "Design posts to support saves, shares, and enquiry responses, while also creating talking points for the sales call.": "تصميم المنشورات لتخدم الحفظ والمشاركة والرد على الاستفسارات، وتصلح كنقاط نقاش أثناء المكالمة البيعية.",
  "Deliverables": "المخرجات",
  "An educational post series about bathroom planning, plumbing, and TV walls.": "سلسلة منشورات تعليمية حول التخطيط للحمام والسباكة وجدار التلفزيون.",
  "Headlines and copy that can expand into short videos, stories, and mini-guides.": "عناوين ونصوص قابلة للتوسع إلى فيديوهات قصيرة وقصص وأدلة مصغرة.",
  "A measurement path that links content to conversations and site-visit requests.": "مسار قياس يربط المحتوى بالمحادثات وطلبات معاينة الموقع.",
  "Measurement plan": "خطة القياس",
  "Awareness:": "الوعي:",
  "Reach and video views.": "الوصول ومشاهدات الفيديو.",
  "Engagement:": "التفاعل:",
  "Saves, shares, and meaningful comments.": "الحفظ والمشاركة والتعليقات النوعية.",
  "Interest:": "الاهتمام:",
  "Messages and service enquiries.": "الرسائل والاستفسارات حول الخدمة.",
  "Conversion:": "التحويل:",
  "Site-visit requests and bookings where tracking is available.": "طلبات معاينة الموقع والحجوزات عند توفر التتبع.",
  "Result": "النتيجة",
  "The gallery includes a bathroom-planning guide, planning the TV wall before finishing, and preventing plumbing problems early. Before naming any numeric result, the page owner, publishing period, post links, and resulting enquiries or site-visit requests must be confirmed.": "تشمل النماذج في المعرض دليل تخطيط الحمام، التخطيط لجدار التلفزيون قبل التشطيب، وتجنب مشكلات السباكة مبكراً. قبل تسمية أي نتيجة رقمية، يجب تأكيد اسم الصفحة المالكة للمحتوى وفترة النشر وروابط المنشورات وعدد الاستفسارات أو طلبات المعاينة الناتجة.",
  "This will be fully replaced with approved page and sales data.": "ستُستبدل بالكامل بأرقام الصفحة وبيانات المبيعات المعتمدة.",
  "Sample result over 60 days": "نموذج نتيجة خلال 60 يوماً",
  "Saves": "مرات الحفظ",
  "New WhatsApp conversations or messages": "محادثات واتساب أو رسائل جديدة",
  "Site-visit requests": "طلبات معاينة موقع",
  "Operations manager, content writing and publishing, quality management, and reporting": "مديرة عمليات، كتابة ونشر المحتوى، إدارة الجودة، وإعداد التقارير",
  "A professional draft that does not reveal client-account names or confidential results.": "مسودة مهنية؛ لا تكشف أسماء الحسابات أو نتائجها السرية.",
  "Serving several accounts requires more than good ideas. It needs a system that gets the right idea out at the right time with a consistent standard of quality. This example shows how operations management creates client value: clearer output, more reliable reviews, and content decisions informed by market signals.": "خدمة عدة حسابات لا تحتاج إلى أفكار جيدة فقط؛ بل تحتاج إلى نظام يضمن وصول الفكرة المناسبة في الوقت المناسب وبالمستوى نفسه من الجودة. يوضح هذا النموذج كيف تُترجم إدارة العمليات إلى قيمة ملموسة للعميل: مخرجات أوضح، مراجعات أكثر انتظاماً، وقرارات محتوى مستندة إلى إشارات السوق.",
  "Operational challenge": "التحدي التشغيلي",
  "Multiple accounts, requirements, and approvals while maintaining a consistent quality standard.": "تعدد الحسابات والمتطلبات والموافقات مع الحفاظ على مستوى ثابت من الجودة.",
  "Turning industry news and social signals into relevant topics for each brand.": "تحويل الأخبار والإشارات الاجتماعية إلى موضوعات مناسبة لكل علامة تجارية.",
  "The need for reports that help the team and client see what has been delivered and what needs improvement.": "الحاجة إلى تقارير تساعد الفريق والعميل على رؤية ما تم إنجازه وما يحتاج إلى تحسين.",
  "Approach": "المنهجية",
  "Workflow organisation:": "تنظيم سير العمل:",
  "Assign responsibilities, track delivery, and prepare clear team reports.": "توزيع المسؤوليات ومتابعة التنفيذ وإعداد تقارير واضحة للفريق.",
  "Content research:": "بحث المحتوى:",
  "Use social listening, independent sources, and industry-news monitoring to identify relevant topics and ideas.": "استخدام الاستماع الاجتماعي والمصادر المستقلة ومتابعة أخبار القطاع لاكتشاف موضوعات وأفكار ذات صلة.",
  "Production and review:": "إنتاج ومراجعة:",
  "Write and publish content, then edit and review it for quality and consistency.": "كتابة المحتوى ونشره، ثم تحريره ومراجعته لضبط الجودة والاتساق.",
  "Continuous improvement:": "تحسين مستمر:",
  "Turn feedback and approved performance data into better topics, copy, and publishing cadence.": "تحويل الملاحظات وبيانات الأداء المعتمدة إلى تحسينات في الموضوعات والصياغة وإيقاع النشر.",
  "Client value": "القيمة للعميل",
  "An operational point of contact that connects strategy with day-to-day delivery.": "نقطة اتصال تشغيلية تربط الاستراتيجية بالتنفيذ اليومي.",
  "More consistent editorial quality across content types and accounts.": "جودة تحريرية أكثر اتساقاً عبر أنواع المحتوى والحسابات.",
  "Reports that make review and decision-making easier rather than simply handing over posts.": "تقارير تُسهّل المراجعة واتخاذ القرار بدلاً من الاكتفاء بتسليم المنشورات.",
  "A practical foundation for scaling production without losing brand identity or audience relevance.": "أساس عملي لتوسيع الإنتاج دون فقدان هوية العلامة أو صلة المحتوى بالجمهور.",
  "These are proposed operational indicators, not actual results for any client account.": "هذه مؤشرات تشغيلية مقترحة وليست نتائج فعلية لأي حساب عميل.",
  "Sample result over one quarter": "نموذج نتيجة خلال ربع سنة",
  "Active accounts under management": "حسابات نشطة تحت الإدارة",
  "Content assets produced and published": "أصول محتوى تم إنتاجها ونشرها",
  "On-time delivery": "التسليم في الموعد",
  "First-round approval": "الموافقة من المراجعة الأولى",
  "Average review rounds per asset": "متوسط جولات المراجعة لكل قطعة",
  "Periodic reports delivered": "التقارير الدورية المُسلَّمة",
  "What is needed for the final version": "ما يلزم لإكمال النسخة النهائية",
  "Approve the client names that may be published, define each account scope, add before-and-after examples, and include approved KPIs or testimonials. This version protects account confidentiality and does not claim unapproved results.": "اعتماد أسماء العملاء المسموح بالنشر عنها، تحديد نطاق كل حساب، أمثلة قبل/بعد، ومؤشرات أداء أو شهادات معتمدة. تُحافظ هذه النسخة على سرية الحسابات ولا تدّعي نتائج لم يتم اعتمادها.",
  "Jana Adel — Social media expert and content creator": "جنا عادل — خبيرة وسائل التواصل الاجتماعي وصانعة محتوى",
  "Jana Adel's portfolio: Social media expert, content creator, and digital marketing trainer, specialising in marketing research and market strategy.": "ملف أعمال جنا عادل: خبيرة وسائل التواصل الاجتماعي وصانعة محتوى ومدربة تسويق رقمي، متخصصة في أبحاث التسويق واستراتيجية السوق.",
  "Learn about Jana Adel, Social media expert, content creator, and digital marketing trainer.": "تعرّف على جنا عادل، خبيرة وسائل التواصل الاجتماعي وصانعة محتوى ومدربة تسويق رقمي.",
  "Jana Adel's work in social media, content, research, and market strategy": "أعمال جنا عادل في وسائل التواصل الاجتماعي والمحتوى والأبحاث واستراتيجية السوق",
  "Case study image": "صورة من دراسة الحالة",
  "Related case studies": "دراسات حالة ذات صلة",
  "Page not found": "الصفحة غير موجودة",
  "The page you are looking for does not exist.": "الصفحة التي تبحث عنها غير موجودة.",
  "Portfolio built with": "صُمم هذا الملف باستخدام",
  "Please enter a valid email address.": "يرجى إدخال بريد إلكتروني صحيح.",
  "Email address": "البريد الإلكتروني",
  "Subscribe": "اشتراك",
  "This page is password protected": "هذه الصفحة محمية بكلمة مرور",
  "Password": "كلمة المرور",
  "Submit": "إرسال",
  "Just now": "الآن",
  "September 8, 2026": "٨ سبتمبر ٢٠٢٦",
  "Cairo, Egypt": "القاهرة، مصر",
  "Arabic, English": "العربية، الإنجليزية",
  "Ahmed Ali Finishing and Décor": "أحمد علي للتشطيبات والديكور",
  "Horus": "حورس",
  "ELADL MEDIA CO.": "العدل ميديا",
  "Download portfolio PDF": "تحميل ملف الأعمال بصيغة PDF",
  "Social media content creator and strategist": "صانعة محتوى واستراتيجية وسائل التواصل الاجتماعي",
  "I don't start with “What should we post today?” I start with “What does the audience need to understand, feel, or do?”": "لا أبدأ بسؤال: «ماذا سننشر اليوم؟» بل أبدأ بسؤال: «ما الذي يحتاج الجمهور إلى فهمه أو الشعور به أو فعله؟»",
  "I'm a social media content creator and strategist focused on turning business ideas into clear, useful, and visually strong content. My work goes beyond designing individual posts: I develop content directions, build recurring series, translate technical or complicated information into audience-friendly stories, write Arabic copy, direct the visual concept, and turn one business objective into multiple content ideas across a consistent brand system.": "أنا صانعة محتوى واستراتيجية لوسائل التواصل الاجتماعي، أركز على تحويل أفكار الأعمال إلى محتوى واضح ومفيد وقوي بصرياً. يتجاوز عملي تصميم المنشورات الفردية؛ فأطور اتجاهات المحتوى، وأبني سلاسل متكررة، وأحوّل المعلومات الفنية أو المعقدة إلى قصص سهلة للجمهور، وأكتب المحتوى العربي، وأقود الفكرة البصرية، وأحوّل هدفاً واحداً للأعمال إلى أفكار محتوى متعددة داخل نظام علامة تجارية متسق.",
  "I work hands-on from idea and research through creative direction, design, caption writing, and publishing—so I understand how every piece needs to work together, not only how each piece looks.": "أعمل بشكل مباشر من الفكرة والبحث مروراً بالتوجيه الإبداعي والتصميم وكتابة النصوص والنشر؛ لذلك أفهم كيف يجب أن تعمل كل العناصر معاً، وليس فقط كيف يبدو كل عنصر منها.",
  "What I can actually handle:": "ما يمكنني تنفيذه فعلياً:",
  "Content strategy & planning · Content pillars · Content ideation · Copywriting · Creative direction · Social media design · Educational content · Brand consistency · Reels concepts & scripts · Community-focused content": "استراتيجية وتخطيط المحتوى · ركائز المحتوى · ابتكار الأفكار · كتابة المحتوى · التوجيه الإبداعي · تصميم وسائل التواصل · المحتوى التعليمي · اتساق العلامة التجارية · أفكار وسيناريوهات الريلز · محتوى يركز على المجتمع",
  "Content strategy and planning": "استراتيجية وتخطيط المحتوى",
  "Build content directions, pillars, recurring series, and publishing plans around the audience, the business objective, and the role each piece of content needs to play.": "بناء اتجاهات المحتوى وركائزه وسلاسله المتكررة وخطط النشر حول الجمهور والهدف التجاري والدور الذي يجب أن تؤديه كل قطعة محتوى.",
  "Content pillars, ideation, calendars": "ركائز المحتوى والأفكار والجداول",
  "Content creation and creative direction": "صناعة المحتوى والتوجيه الإبداعي",
  "Turn complex ideas into clear Arabic copy, visual concepts, educational posts, social-media designs, and Reels concepts that work together as a recognisable brand system.": "تحويل الأفكار المعقدة إلى نصوص عربية واضحة ومفاهيم بصرية ومنشورات تعليمية وتصاميم لوسائل التواصل وأفكار ريلز تعمل معاً كنظام علامة تجارية سهل التعرّف عليه.",
  "Arabic copywriting, design, Reels concepts": "كتابة المحتوى العربي والتصميم وأفكار الريلز",
  "Creative direction and brand consistency": "التوجيه الإبداعي واتساق العلامة التجارية",
  "Audience insight and community-focused content": "رؤى الجمهور والمحتوى الذي يركز على المجتمع",
  "Use questions, audience signals, competitor context, and market research to uncover what people need to understand, feel, or do—and turn those insights into more useful content.": "استخدام الأسئلة وإشارات الجمهور وسياق المنافسين وأبحاث السوق لاكتشاف ما يحتاج الناس إلى فهمه أو الشعور به أو فعله، وتحويل هذه الرؤى إلى محتوى أكثر فائدة.",
  "Research, listening, and audience questions": "البحث والاستماع وأسئلة الجمهور",
  "Social media management and optimisation": "إدارة وتحسين وسائل التواصل الاجتماعي",
  "Plan platform-appropriate content, guide publishing, review performance signals, and use what the audience does next to improve future content decisions.": "تخطيط محتوى مناسب لكل منصة وتوجيه النشر ومراجعة إشارات الأداء واستخدام ما يفعله الجمهور لاحقاً لتحسين قرارات المحتوى المستقبلية.",
  "Publishing, community, and performance learning": "النشر والمجتمع والتعلم من الأداء",
  "Cube-K nutrient-release timeline": "الخط الزمني لإتاحة عناصر Cube-K",
  "A product-education visual that makes the timing of nutrient availability easier to understand at a glance.": "تصميم تعليمي للمنتج يوضح توقيت إتاحة العناصر الغذائية بسهولة من النظرة الأولى.",
  "Plant hormones, made approachable": "هرمونات النبات بطريقة سهلة",
  "An educational concept that translates plant-growth science into a friendly, memorable social-media story.": "فكرة تعليمية تترجم علم نمو النبات إلى قصة ودودة وسهلة التذكر على وسائل التواصل.",
  "Plants respond to signals": "النباتات تستجيب للإشارات",
  "A visual-led explanation that gives a technical crop topic an immediate and audience-friendly hook.": "شرح تقوده الصورة يمنح موضوعاً فنياً عن المحاصيل خطافاً فورياً وقريباً من الجمهور.",
  "Every growth stage has a priority": "لكل مرحلة نمو أولوية",
  "A Sunny product visual that connects plant development to the right nutritional focus at the right time.": "تصميم لمنتج صني يربط تطور النبات بالتركيز الغذائي المناسب في الوقت المناسب.",
  "Fruit quality is more than size": "جودة الثمرة أكبر من حجمها",
  "A product-storytelling design that connects Cube-K to the quality signals growers care about.": "تصميم لسرد قصة المنتج يربط Cube-K بإشارات الجودة التي يهتم بها المزارعون.",
  "Every harvest starts with the soil": "كل حصاد يبدأ من الأرض",
  "A brand-led visual that turns agricultural roots and origin into a memorable story for Sunny.": "تصميم تقوده العلامة يحول الجذور والأصل الزراعي إلى قصة لا تُنسى لمنتج صني.",
  "Growth begins underground": "النمو يبدأ تحت الأرض",
  "A root-system visual that makes an invisible agricultural benefit clear before introducing the product.": "تصميم لجذور النبات يوضح فائدة زراعية غير مرئية قبل تقديم المنتج.",
  "One product, four quality benefits": "منتج واحد وأربع فوائد للجودة",
  "A bold Cube-K product concept that organises multiple crop-quality benefits into one clear visual message.": "فكرة جريئة لمنتج Cube-K تنظم عدة فوائد لجودة المحصول في رسالة بصرية واحدة واضحة.",
  "Stronger roots, stronger yield": "جذور أقوى ومحصول أقوى",
  "A high-impact root visual that helps growers connect a healthy underground system with a stronger crop outcome.": "تصميم قوي للجذور يساعد المزارعين على ربط النظام الصحي تحت الأرض بنتيجة محصول أقوى.",
  "From soil to a bigger story": "من الأرض إلى قصة أكبر",
  "A visual narrative that gives the agricultural brand a broader, more emotional content angle.": "سرد بصري يمنح العلامة الزراعية زاوية محتوى أوسع وأكثر تأثيراً عاطفياً.",
  "A home worth imagining": "منزل يستحق أن تتخيله",
  "An aspirational brand visual that pairs a finished interior with an emotional invitation to imagine the final result.": "تصميم ملهم للعلامة يجمع بين مساحة داخلية مكتملة ودعوة عاطفية لتخيل النتيجة النهائية.",
  "Apartment handover mistake Reel": "ريل خطأ استلام الشقة",
  "A short-form video concept that turns a common handover decision into a clear, practical warning.": "فكرة فيديو قصير تحول قراراً شائعاً عند الاستلام إلى تنبيه عملي وواضح.",
  "Kitchen finishing mistake Reel": "ريل خطأ تشطيب المطبخ",
  "An educational Reel that uses a familiar kitchen decision to make good execution easier to understand.": "ريل تعليمي يستخدم قراراً مألوفاً في المطبخ لتسهيل فهم التنفيذ الصحيح.",
  "Waterproofing advice Reel": "ريل نصيحة العزل المائي",
  "A practical video format that makes a hidden waterproofing decision visible before work begins.": "صيغة فيديو عملية تجعل قرار العزل المائي المخفي واضحاً قبل بدء العمل.",
  "Your home has a story Reel": "ريل لبيتك حكاية",
  "A brand-storytelling format that gives the finishing page a warmer, community-focused voice.": "صيغة لسرد قصة العلامة تمنح صفحة التشطيبات صوتاً أكثر دفئاً وتركيزاً على المجتمع.",
  "Protect wood doors early Reel": "ريل احمِ الأبواب الخشبية مبكراً",
  "A mistake-led Reel that turns a costly finishing detail into an actionable preparation message.": "ريل يقوده خطأ شائع يحول تفصيلة تشطيب مكلفة إلى رسالة تحضير قابلة للتنفيذ.",
  "Electrical socket mistake Reel": "ريل خطأ مقبس الكهرباء",
  "A short-form educational warning that shows why electrical-point planning belongs before finishing.": "تنبيه تعليمي قصير يوضح لماذا يجب التخطيط لنقاط الكهرباء قبل التشطيب.",
  "Ahmed Ali — building a finishing content brand from the ground up": "أحمد علي — بناء علامة محتوى للتشطيبات من الصفر",
  "A social-media system that turns hidden workmanship and homeowner decisions into clear, useful content.": "نظام لوسائل التواصل يحول جودة العمل المخفية وقرارات أصحاب المنازل إلى محتوى واضح ومفيد.",
  "Horus — agricultural content built from understanding": "حورس — محتوى زراعي مبني على الفهم",
  "A social-media system that makes agricultural knowledge useful, visual, and relevant to growers.": "نظام لوسائل التواصل يجعل المعرفة الزراعية مفيدة وبصرية ومرتبطة باحتياجات المزارعين.",
  "Brand identity, page setup, social-media strategy, content strategy, creative direction, Arabic copywriting, design, Reels concepts, publishing, and performance review": "هوية العلامة وإعداد الصفحة واستراتيجية وسائل التواصل واستراتيجية المحتوى والتوجيه الإبداعي وكتابة المحتوى العربي والتصميم وأفكار الريلز والنشر ومراجعة الأداء",
  "Ahmed Ali began with a blank social-media page: no established visual system, no content pillars, no recurring series, and no defined voice. The objective was never simply to fill a feed with attractive interiors. It was to build a recognisable content brand that helps homeowners understand the thinking behind quality finishing.": "بدأ أحمد علي بصفحة خالية على وسائل التواصل: بلا نظام بصري ثابت أو ركائز للمحتوى أو سلاسل متكررة أو صوت محدد. لم يكن الهدف ملء الخلاصة بصور داخلية جذابة فحسب، بل بناء علامة محتوى يسهل تمييزها وتساعد أصحاب المنازل على فهم التفكير وراء التشطيب الجيد.",
  "Starting point": "نقطة البداية",
  "The first question was not “What should we post?” but “What should this brand be known for?” The page needed to feel clean, premium, architectural, and professional—without becoming distant from homeowners who are making expensive decisions and may not know the technical language of finishing.": "لم يكن السؤال الأول «ماذا سننشر؟» بل «بماذا يجب أن تُعرف هذه العلامة؟». كان يجب أن تبدو الصفحة نظيفة وفاخرة ومعمارية واحترافية من دون أن تصبح بعيدة عن أصحاب المنازل الذين يتخذون قرارات مكلفة وقد لا يعرفون اللغة الفنية للتشطيبات.",
  "I created the visual identity and the social-media environment around it: logo usage, typography, colour, layout, image treatment, information hierarchy, and a consistent way for every post to feel part of one brand. Consistency was designed as a system, not a template. Each topic could look different while still belonging to Ahmed Ali.": "أنشأت الهوية البصرية والبيئة الخاصة بها على وسائل التواصل: استخدام الشعار والخطوط والألوان والتخطيط ومعالجة الصور وتسلسل المعلومات، وطريقة متسقة تجعل كل منشور جزءاً من علامة واحدة. صُمم الاتساق كنظام لا كقالب؛ فلكل موضوع شكله الخاص مع بقاء انتمائه لأحمد علي.",
  "Audience insight": "رؤى الجمهور",
  "Homeowners do not usually want a lesson in finishing. They want to avoid decisions they will regret after move-in. Their questions are practical: What is hidden behind the wall? What needs to be decided before it is too late? What am I really paying for? Which detail will become expensive to change later?": "لا يريد أصحاب المنازل درساً في التشطيبات عادةً، بل يريدون تجنب قرارات سيندمون عليها بعد السكن. أسئلتهم عملية: ما المخفي خلف الحائط؟ ما الذي يجب حسمه قبل فوات الأوان؟ مقابل ماذا أدفع فعلياً؟ وما التفصيلة التي ستصبح مكلفة عند تغييرها لاحقاً؟",
  "That insight shaped the page. Technical information became useful stories, common mistakes became hooks, customer questions became educational assets, and invisible workmanship became something the audience could see and understand.": "هذه الرؤية شكلت الصفحة: تحولت المعلومات الفنية إلى قصص مفيدة، والأخطاء الشائعة إلى خطافات، وأسئلة العملاء إلى أصول تعليمية، والعمل المخفي إلى شيء يراه الجمهور ويفهمه.",
  "Content system": "نظام المحتوى",
  "The strategy developed around repeatable series rather than disconnected posts.": "تطورت الاستراتيجية حول سلاسل قابلة للتكرار بدلاً من منشورات منفصلة.",
  "The result is a system where one customer problem can become an educational post, a hidden-detail visual, a mistake story, a decision post, an interactive question, a Reel concept, and a brand message.": "والنتيجة نظام يمكن فيه لمشكلة واحدة لدى العميل أن تتحول إلى منشور تعليمي أو تصميم لتفصيلة مخفية أو قصة خطأ أو منشور قرار أو سؤال تفاعلي أو فكرة ريل أو رسالة للعلامة.",
  "Visual storytelling and AI-assisted production": "السرد البصري والإنتاج المدعوم بالذكاء الاصطناعي",
  "The visual does more than make a post attractive. It explains part of the idea. A wall is not only a wall; it can reveal the electrical planning inside it. A bathroom image can show why the drainage layer below the surface matters. An AC unit can become a story about installation details.": "الصورة تفعل أكثر من جعل المنشور جذاباً؛ فهي تشرح جزءاً من الفكرة. فالحائط ليس حائطاً فقط، بل يمكنه كشف تخطيط الكهرباء داخله. وصورة الحمام يمكنها أن توضح أهمية طبقة الصرف تحت السطح. ووحدة التكييف قد تصبح قصة عن تفاصيل التركيب.",
  "AI is used as an execution tool when a specific visual is difficult to source through photography. The creative direction still begins with the audience, the decision, the hook, the scene, and the brand. Outputs are selected, refined, and integrated into the final content system—not treated as the strategy itself.": "يُستخدم الذكاء الاصطناعي كأداة تنفيذ عندما يصعب الحصول على صورة محددة بالتصوير. لكن التوجيه الإبداعي يبدأ دائماً بالجمهور والقرار والخطاف والمشهد والعلامة. يتم اختيار المخرجات وتحسينها ودمجها في نظام المحتوى النهائي، لا التعامل معها كاستراتيجية بحد ذاتها.",
  "Selected production": "نماذج مختارة من الإنتاج",
  "Content cycle and performance learning": "دورة المحتوى والتعلم من الأداء",
  "Publishing is not the final step. Content is reviewed through reach, video views, interactions, audience activity, and messaging actions to identify what earns attention, what creates useful interaction, which format deserves another test, and what should change in the next cycle.": "النشر ليس الخطوة الأخيرة. يُراجع المحتوى من خلال الوصول ومشاهدات الفيديو والتفاعلات ونشاط الجمهور وإجراءات المراسلة لتحديد ما يجذب الانتباه وما يخلق تفاعلاً مفيداً وأي صيغة تستحق اختباراً آخر وما الذي يجب تغييره في الدورة التالية.",
  "Create → Publish → Measure → Learn → Improve": "إنشاء ← نشر ← قياس ← تعلم ← تحسين",
  "The outcome": "النتيجة",
  "Ahmed Ali moved from a blank social-media page to a content brand with a clear standard of communication: not simply “look at our finished work,” but “understand the thinking behind our work.” The content demonstrates expertise through planning, details, correct execution, and long-term thinking—showing the standard instead of only claiming it.": "انتقل أحمد علي من صفحة خالية على وسائل التواصل إلى علامة محتوى بمعيار واضح للتواصل: ليس «انظر إلى أعمالنا المكتملة» فقط، بل «افهم التفكير وراء أعمالنا». ويثبت المحتوى الخبرة عبر التخطيط والتفاصيل والتنفيذ الصحيح والتفكير طويل المدى، فيُظهر المعيار بدلاً من الاكتفاء بادعائه.",
  "Page creation, social-media strategy, content planning, agricultural content, creative direction, Arabic copywriting, design, publishing, page management, and performance learning": "إنشاء الصفحة واستراتيجية وسائل التواصل وتخطيط المحتوى والمحتوى الزراعي والتوجيه الإبداعي وكتابة المحتوى العربي والتصميم والنشر وإدارة الصفحة والتعلم من الأداء",
  "Horus brought together two parts of my background: Agriculture and content creation. The brand had an existing logo but no established social-media presence. My role was to turn that identity into a page with a clear visual direction, a useful tone of voice, and a content system that could speak about Sunny Fertilizer and Cube-K without becoming a repetitive product catalogue.": "جمع حورس بين جانبين من خلفيتي: الزراعة وصناعة المحتوى. كانت لدى العلامة هوية وشعار موجودان، لكن بلا حضور ثابت على وسائل التواصل. كان دوري تحويل الهوية إلى صفحة باتجاه بصري واضح ونبرة صوت مفيدة ونظام محتوى يمكنه الحديث عن صني وCube-K دون أن يتحول إلى كتالوج منتجات مكرر.",
  "The product scope was focused, but the audience’s needs were much wider. A grower is not opening social media looking for another product sheet. They are thinking about their crop, what they are noticing, what might be out of balance, and which decision will help them get a better result.": "كان نطاق المنتجات محدداً، لكن احتياجات الجمهور أوسع بكثير. لا يفتح المزارع وسائل التواصل بحثاً عن ورقة منتج أخرى، بل يفكر في محصوله وما يلاحظه وما قد يكون غير متوازن والقرار الذي سيساعده على نتيجة أفضل.",
  "The content needed to make each product relevant through real agricultural context. The approach moved from “here is the product and what it does” to “here is what is happening with the crop, why it matters, and where the product fits.”": "كان على المحتوى أن يجعل كل منتج ذا صلة عبر سياق زراعي حقيقي. وانتقل النهج من «هذا هو المنتج وما يفعله» إلى «هذا ما يحدث للمحصول، ولماذا يهم، وأين يناسب المنتج».",
  "Understanding before simplifying": "الفهم قبل التبسيط",
  "Agricultural information must be understood before it can be made simple. The process begins with the agricultural logic: what the plant needs, the problem or misconception, the crop signal, the timing, and the expected outcome. From there, the content angle, hook, explanation, visual, and product role can be designed accurately.": "يجب فهم المعلومة الزراعية قبل تبسيطها. تبدأ العملية بالمنطق الزراعي: ما يحتاجه النبات، والمشكلة أو المفهوم الخاطئ، وإشارة المحصول، والتوقيت، والنتيجة المتوقعة. ومن هناك يمكن تصميم زاوية المحتوى والخطاف والشرح والصورة ودور المنتج بدقة.",
  "Agricultural understanding → Audience question → Clear hook → Simple accurate explanation → Visual concept → Relevant product": "فهم زراعي ← سؤال الجمهور ← خطاف واضح ← شرح بسيط ودقيق ← مفهوم بصري ← منتج ذو صلة",
  "The aim is not to make the science less accurate. It is to make the science easier to understand and more useful in a fast-moving social-media environment.": "الهدف ليس جعل العلم أقل دقة، بل جعله أسهل فهماً وأكثر فائدة في بيئة سريعة الحركة على وسائل التواصل.",
  "The page gives different pieces of content different jobs:": "تمنح الصفحة كل قطعة محتوى وظيفة مختلفة:",
  "One product can become an educational post, a problem-awareness visual, a technical explanation, a product-focused story, a comparison, an interactive question, or a short-form video concept. The product stays the same; the audience need and the conversation change.": "يمكن لمنتج واحد أن يصبح منشوراً تعليمياً أو تصميماً للتوعية بمشكلة أو شرحاً فنياً أو قصة تركز على المنتج أو مقارنة أو سؤالاً تفاعلياً أو فكرة فيديو قصير. يبقى المنتج نفسه، لكن حاجة الجمهور والحوار يتغيران.",
  "Visual direction and AI-assisted production": "التوجيه البصري والإنتاج المدعوم بالذكاء الاصطناعي",
  "The visual system was designed to work across education, product communication, and brand storytelling without making every post look the same. Plants, roots, fruit quality, crop signals, and product packs all carry a role in explaining the message—not simply filling the layout.": "صُمم النظام البصري ليعمل عبر التعليم والتواصل عن المنتجات وسرد قصة العلامة دون أن تبدو المنشورات متشابهة. للنباتات والجذور وجودة الثمار وإشارات المحصول وعبوات المنتجات دور في شرح الرسالة، لا مجرد ملء التصميم.",
  "AI-assisted visuals are evaluated through an agricultural lens. A plant, symptom, or crop relationship must make technical sense before it is used. The tool helps execute a specific creative direction; agricultural understanding guides the selection and refinement.": "تُقيّم التصاميم المدعومة بالذكاء الاصطناعي بمنظور زراعي. يجب أن يبدو النبات أو العرض أو علاقة المحصول منطقياً فنياً قبل استخدامه. تساعد الأداة في تنفيذ اتجاه إبداعي محدد، بينما يوجه الفهم الزراعي الاختيار والتحسين.",
  "The page is managed as a living system. Publishing creates information about which questions attract attention, which hooks earn a pause, which formats create interaction, and which ideas deserve another variation. Those signals feed the next plan.": "تُدار الصفحة كنظام حي. فالنشر يخلق معلومات حول الأسئلة التي تجذب الانتباه والخطافات التي تدفع للتوقف والصيغ التي تصنع التفاعل والأفكار التي تستحق نسخة أخرى. وتغذي هذه الإشارات الخطة التالية.",
  "Plan → Create → Publish → Measure → Learn → Adjust": "خطط ← أنشئ ← انشر ← قس ← تعلم ← عدّل",
  "Horus became more than a channel for two products. It became a social-media presence where agricultural knowledge, useful storytelling, Arabic copywriting, and a consistent visual direction work together. The content helps growers understand the context first—then see where Sunny Fertilizer and Cube-K belong in the conversation.": "أصبح حورس أكثر من قناة لمنتجين؛ بل حضوراً على وسائل التواصل تعمل فيه المعرفة الزراعية والسرد المفيد وكتابة المحتوى العربي واتجاه بصري متسق معاً. يساعد المحتوى المزارعين على فهم السياق أولاً، ثم رؤية مكان صني وCube-K في الحوار.",
  "Performance results": "نتائج الأداء",
  "Result over 90 days": "النتيجة خلال 90 يوماً",
  "Result over 60 days": "النتيجة خلال 60 يوماً",
  "Result over one quarter": "النتيجة خلال ربع سنة",
  "Technical expertise becomes more valuable on social media when it is organised around the audience's real questions, then delivered through a recognisable visual system.": "تصبح الخبرة التقنية أكثر قيمة على وسائل التواصل الاجتماعي عندما تُنظَّم حول أسئلة الجمهور الحقيقية وتُقدَّم عبر نظام بصري واضح ومميز.",
  "Structured operations connect strategy to delivery, helping client accounts maintain editorial quality and scale their content output without losing audience relevance.": "تربط العمليات المنظمة بين الاستراتيجية والتنفيذ، وتساعد حسابات العملاء على الحفاظ على الجودة التحريرية وتوسيع إنتاج المحتوى دون فقدان صلته بالجمهور.",
};

const arabicToEnglish = Object.fromEntries(
  Object.entries(englishToArabic).map(([english, arabic]) => [arabic, english]),
);

export function translateText(text: string, language: Language) {
  const prefix = text.match(/^\s*/)?.[0] ?? "";
  const suffix = text.match(/\s*$/)?.[0] ?? "";
  const value = text.trim().replace(/\s+/g, " ");
  if (!value) return text;

  const translated = language === "ar" ? englishToArabic[value] : arabicToEnglish[value];
  return translated ? `${prefix}${translated}${suffix}` : text;
}
